verbose: true
input_file: ""
output: ""
mcmc_steps: 16
variance_threshold: 0.015
workers: null
model: openai/gpt-4o-mini
api_key: null
api_base: null
temperature: 0.8
reasoning_effort: null
test_model: "openai/gpt-5.3-codex"
test_api_key: null
test_api_base: null
analysis_tool: semgrep
num_rollouts: 1
no_successes: false
language: python
