verbose: true
model: openai/gpt-4o-mini
temperature: 1.0
cwes: []
use_top_25: true
min_samples: 10
output_dir: ./output/sweeps/
api_key: null
api_base: null
test_model: "openai/gpt-5.3-codex"
test_api_key: null
test_api_base: null
num_rollouts: 10
reasoning_effort: null
analysis_tool: semgrep
checkpoint: null
tk_checkpoint: null
tk_model: null
coder_prompt: null
language: python
