runs:
  - name: gpt-4o-mini
    overrides:
      - model=openai/gpt-4o-mini
    api_key_env: OPENAI_API_KEY

  - name: gpt-5-nano
    overrides:
      - model=openai/gpt-5-nano-2025-08-07
    api_key_env: OPENAI_API_KEY

  - name: gpt-5-mini
    overrides:
      - model=openai/gpt-5-mini-2025-08-07
    api_key_env: OPENAI_API_KEY

  - name: gpt-5.2
    overrides:
      - model=openai/gpt-5.2-2025-12-11
    api_key_env: OPENAI_API_KEY

  - name: gpt-5.2-codex
    overrides:
      - model=openai/gpt-5.2-codex
    api_key_env: OPENAI_API_KEY

  - name: gpt-oss-120b
    overrides:
      - model=openai/gpt-oss-120b
      - api_base=http://longbeach.stanford.edu:11401/v1
    api_key_env: "hello!"

  - name: gpt-oss-20b
    overrides:
      - model=openai/gpt-oss-20b
      - api_base=http://longbeach.stanford.edu:11401/v1
    api_key_env: "hello!"


  - name: qwen3-coder-bend
    overrides:
      - model=qwen3-coder-30B-a3b-Instruct # use lower-case name without "qwen/" prefix to avoid vLLM/OpenAI-compatible server issues
      - api_base=http://bend.stanford.edu:11401/v1
    api_key_env: "hello!"

  - name: glm-47-flash-bend
    overrides:
      - model=glm-4.7-flash
      - api_base=http://bend.stanford.edu:11402/v1
    api_key_env: "hello!"